[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "drosera-contracts/=lib/drosera-contracts/src/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]

[profile.default.fuzz]
runs = 1000

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[doc]
ignore = ["**/*.t.sol"]
out = "docs"
repository = "https://github.com/drosera-network"
